### ISSUE TITLE
Heh, lol> Russian Translation 

### ISSUE THREAD

**Issue by ghost** [HelloWorld017/ToAruPG#1]
MUST_INGAME: "Вы должны использовать эту команду в игре!"
NOT_VALID_PLAYER: "Вау! Была ошибка. Извините за неудобства. Почему бы вам не подключите?"
NO_SKILL_ITEM: "Элемент, который вы держите в руках, не навык."
LV: "Lv"
INSUFFICIENT_SP: "Недостаточно SP!"
INVESTED_SP: "Успешно инвестировано 1 SP."
INSUFFICIENT_AP: "Недостаточно AP!"
UNKNOWN_STATUS: "Неизвестная способность получена. /ability для просмотра способностей."
INVESTED_AP: "Успешно инвестировано  1 AP."
STATUS: "Способность"
AP: "AP"
SP: "SP"
MAXHP: "Макс. HP"
MAXMP: "Макс. MP"
STR: "STR"
INT: "INT"
DEX: "DEX"
LUK: "LUK"
ADVENTURER: Авантюрист
NO_MANA: "Недостаточно маны!"

**Comment by HelloWorld017** [comment]
Thank you! I'll add these on the next commit!

**Comment by ghost** [comment]
Thank!

**Comment by Seetch** [comment]
You have the social networks?
